//
// objs/nbody_ispc.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC_OBJS_NBODY_ISPC_H
#define ISPC_OBJS_NBODY_ISPC_H

#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus

///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && !defined(__ISPC_NO_EXTERN_C)
extern "C" {
#endif // __cplusplus
    extern void compute_forces(const int32_t n, const float * mass, const float * posx, const float * posy, const float * posz, const float * velx, const float * vely, const float * velz, float * accx, float * accy, float * accz, float * jrkx, float * jrky, float * jrkz, float * gpot, const float eps2);
#if defined(__cplusplus) && !defined(__ISPC_NO_EXTERN_C)
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC_OBJS_NBODY_ISPC_H
